### PR TITLE
Switch client.base to instance data.

### PR DESCRIPTION
**Pull request by b4hand**
@tammybailey, @dlecocq, @matt-peters 

We observed that class data was getting reinitialized when gevent was used making class data unsafe.

### CODE REVIEW

**Review by tammybailey — COMMENTED** [review]
Do we want/need to give `base` a default value?

**Review by dlecocq — APPROVED** [review]
Works for me.

Someday we should rewrite / clean up this atrocity. I don't know what jerk wrote this thing. _cough_cough*

**Comment by b4hand** [comment]
Yes, `base` should have a default value, so we don't make old users of the library specify a new argument.

**Comment by tammybailey** [comment]
ah, good point!

**Pull request merged**
